// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCliVlgpt2Q4r2ZSoVTUWErvZV9y-AjWaE',
    appId: '1:788794383607:web:1ab43593d2755794a487f2',
    messagingSenderId: '788794383607',
    projectId: 'riddle-b4b7b',
    authDomain: 'riddle-b4b7b.firebaseapp.com',
    storageBucket: 'riddle-b4b7b.appspot.com',
    measurementId: 'G-LX5QMQ8VH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXUmI7ihzCkYzW03RU2BrmB57eitV-Ki8',
    appId: '1:788794383607:android:e3f34a923894c16ea487f2',
    messagingSenderId: '788794383607',
    projectId: 'riddle-b4b7b',
    storageBucket: 'riddle-b4b7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnu9Nf--hTr0yGw5VfsPK7DHFNkVwdipU',
    appId: '1:788794383607:ios:9ce88ab50199781ca487f2',
    messagingSenderId: '788794383607',
    projectId: 'riddle-b4b7b',
    storageBucket: 'riddle-b4b7b.appspot.com',
    androidClientId: '788794383607-bk0q3gpb84c1f4g6a6bkl4c5p1rl0i0g.apps.googleusercontent.com',
    iosClientId: '788794383607-qe3rs9ldelr9qg35nr54hjggqnppniip.apps.googleusercontent.com',
    iosBundleId: 'com.higuchiyuya.riddle',
  );
}
